# Mathematical operations using Numpy

In [1]:
import numpy as np

In [2]:
ar1=np.arange(1,10).reshape(3,3)

In [3]:
print(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ar2=np.arange(1,10).reshape(3,3)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Addition


In [5]:
ar1=np.arange(1,10).reshape(3,3)
ar1+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
np.add(ar1,ar2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Substraction

In [8]:
np.subtract(ar1,ar2)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Division

In [9]:
np.divide(ar1,ar2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Multiplication

In [11]:
np.multiply(ar1,ar2)
#or
ar1*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Matrix product or Dot product

In [13]:
ar1@ar2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [14]:
ar1.dot(ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# Max Value

In [15]:
ar1.max()

9

# Index of max value

In [16]:
ar1.argmax()

8

# Row-wise Max Value

In [17]:
ar1.max(axis=1)

array([3, 6, 9])

#  Column-wise Max Value

In [18]:
ar1.max(axis=0)

array([7, 8, 9])

# sum

In [19]:
np.sum(ar1)

45

# Row-wise sum

In [21]:
np.sum(ar1,axis=1)

array([ 6, 15, 24])

#  Column-wise sum

In [23]:
np.sum(ar1,axis=0)

array([12, 15, 18])

# mean

In [24]:
np.mean(ar1)

5.0

# Square Root

In [25]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])