In [1]:
import numpy as np

In [2]:
Array_1d=np.array([1,2,3,4])
print(Array_1d)

[1 2 3 4]


In [3]:
Array_2D=np.array([[1,2,3,4],[1,2,3,4]])
print(Array_2D)


[[1 2 3 4]
 [1 2 3 4]]


In [4]:
Array_2D.shape


(2, 4)

# Numpy Functions

# ->

# arange()

In [11]:
ar_1d=np.arange(1,13)
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
ar_1deven=np.arange(1,12,2)
ar_1deven

array([ 1,  3,  5,  7,  9, 11])

# linspace()


In [9]:
np.linspace(1,5,4) #to make equal difference beetween elements

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()


In [17]:
ar_2d=ar_1d.reshape(2,6) #remember the number of rows and column and divide accordingly else
                            #product of argument in reshape must be equal to size of the array
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()


In [19]:
ar_2d.ravel() #simply converts multi-dimensional array into 1-dimensional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [20]:
ar_2d.ravel() #same as ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [22]:
ar_2d.transpose() #converts row into column and column into row

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [25]:
ar_2d.T  #optional

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])