In [1]:
import numpy as np


In [2]:
ARRAY_3D=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(ARRAY_3D)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
arr=np.ones(5)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('float64')

In [6]:
aa=np.ones((3,4))

In [7]:
print(aa)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
zero=np.zeros(3)
print(zero)

[0. 0. 0.]


In [9]:
np.ones(4,int)

array([1, 1, 1, 1])