# Array slicing

In [1]:
import numpy as np


In [2]:
ar2D=np.arange(1,101).reshape(10,10)

In [3]:
print(ar2D)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [4]:
ar2D[0,0] #it will give you vector element


1

In [5]:
ar2D.ndim

2

In [6]:
ar2D[0] #single Row 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
ar2D[:,0] #single Column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
ar2D[:,0:2] #gives 2 column and all row and last parameter after : is exclusive

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [10]:
ar2D[2:5,2:5] #it will give 2,3 and 4th row and column

array([[23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [11]:
ar2D[:,:]  #whole matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
ar2D.itemsize

4