# Random Sampling

In [3]:
import numpy as np

In [4]:
import random 

In [5]:
np.random.random(1)

array([0.93676971])

In [6]:
np.random.random((3,3))

array([[0.67926212, 0.80799089, 0.09465154],
       [0.12815733, 0.68648087, 0.92943553],
       [0.56389501, 0.40796039, 0.03521104]])

In [10]:
np.random.randint(1,4) #4 is exclusive

1

In [11]:
np.random.randint(1,4,(4,4))

array([[1, 3, 3, 2],
       [1, 3, 3, 2],
       [1, 3, 3, 2],
       [3, 3, 3, 1]])

In [13]:
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 3, 3],
        [1, 3, 3, 3],
        [1, 2, 3, 1],
        [2, 2, 2, 1]],

       [[2, 2, 2, 2],
        [1, 3, 3, 3],
        [1, 2, 2, 3],
        [3, 2, 2, 3]]])

In [16]:
np.random.seed(1) # for getting same random value
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 1, 2],
        [2, 1, 1, 2],
        [1, 2, 1, 3],
        [2, 3, 1, 3]],

       [[2, 3, 1, 1],
        [3, 1, 2, 3],
        [3, 1, 2, 2],
        [3, 1, 3, 2]]])

In [17]:
np.random.seed(1)
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 1, 2],
        [2, 1, 1, 2],
        [1, 2, 1, 3],
        [2, 3, 1, 3]],

       [[2, 3, 1, 1],
        [3, 1, 2, 3],
        [3, 1, 2, 2],
        [3, 1, 3, 2]]])

In [20]:
np.random.randn(3,3)

array([[-0.90312288,  0.17532267,  0.19443089],
       [-0.53524902,  0.77735121,  0.17133845],
       [-0.44285144,  1.70490377,  0.92434585]])

In [22]:
x=[1,2,3,4]
np.random.choice(x)

2

In [24]:
np.random.permutation(x)

array([2, 3, 1, 4])